# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# curl 'http://localhost:8080/MinhBookstoreOrder/api/orders'
#  -H 'Accept: */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Cache-Control: max-age=0'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:5173'
#  -H 'Referer: http://localhost:5173/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62'
#  -H 'sec-ch-ua: "Microsoft Edge";v="111", "Not(A:Brand";v="8", "Chromium";v="111"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1002,"title":"Maps of Meaning","author":"Jordan B. Peterson","description":"","price":2200,"rating":0,"isPublic":false,"categoryId":1001,"featured":false},"quantity":4}]},"customerForm":{"name":"Minh","address":"1212","phone":"5403576025","email":"mng@gmail.com","ccNumber":"4444333311112222","ccExpiryMonth":4,"ccExpiryYear":2023}}'
#  --compressed

POST http://localhost:8080/MinhBookstoreOrder/api/orders
Accept: */*
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
sec-ch-ua: "Microsoft Edge";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1002,
          "title": "Maps of Meaning",
          "author": "Jordan B. Peterson",
          "description": "",
          "price": 2200,
          "rating": 0,
          "isPublic": false,
          "categoryId": 1001,
          "featured": false
        },
        "quantity": 3
      }
    ]
  },
  "customerForm": {
    "name": "Minh",
    "address": "1212",
    "phone": "5403576025",
    "email": "mng@gmail.com",
    "ccNumber": "4444333311112222",
    "ccExpiryMonth": 4,
    "ccExpiryYear": 2023
  }
}

###


###
